use_frameworks!

platform :ios, '13.0'

target 'SwiftyAuthentication_Example' do
  pod 'SwiftyAuthentication', :path => '../'

  target 'SwiftyAuthentication_Tests' do
    inherit! :search_paths

    
  end
end
